/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GeminiRouteImport } from './routes/gemini'
import { Route as ChatNewRouteImport } from './routes/chat-new'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateQuestionsRouteImport } from './routes/api/generate-questions'
import { Route as ApiGeminiQuestionRouteImport } from './routes/api/gemini-question'
import { Route as ApiGeminiFeedbackRouteImport } from './routes/api/gemini-feedback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const GeminiRoute = GeminiRouteImport.update({
  id: '/gemini',
  path: '/gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatNewRoute = ChatNewRouteImport.update({
  id: '/chat-new',
  path: '/chat-new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateQuestionsRoute = ApiGenerateQuestionsRouteImport.update({
  id: '/api/generate-questions',
  path: '/api/generate-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeminiQuestionRoute = ApiGeminiQuestionRouteImport.update({
  id: '/api/gemini-question',
  path: '/api/gemini-question',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeminiFeedbackRoute = ApiGeminiFeedbackRouteImport.update({
  id: '/api/gemini-feedback',
  path: '/api/gemini-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/chat-new': typeof ChatNewRoute
  '/gemini': typeof GeminiRoute
  '/api/gemini-feedback': typeof ApiGeminiFeedbackRoute
  '/api/gemini-question': typeof ApiGeminiQuestionRoute
  '/api/generate-questions': typeof ApiGenerateQuestionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/chat-new': typeof ChatNewRoute
  '/gemini': typeof GeminiRoute
  '/api/gemini-feedback': typeof ApiGeminiFeedbackRoute
  '/api/gemini-question': typeof ApiGeminiQuestionRoute
  '/api/generate-questions': typeof ApiGenerateQuestionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/chat-new': typeof ChatNewRoute
  '/gemini': typeof GeminiRoute
  '/api/gemini-feedback': typeof ApiGeminiFeedbackRoute
  '/api/gemini-question': typeof ApiGeminiQuestionRoute
  '/api/generate-questions': typeof ApiGenerateQuestionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/chat-new'
    | '/gemini'
    | '/api/gemini-feedback'
    | '/api/gemini-question'
    | '/api/generate-questions'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/chat-new'
    | '/gemini'
    | '/api/gemini-feedback'
    | '/api/gemini-question'
    | '/api/generate-questions'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/chat-new'
    | '/gemini'
    | '/api/gemini-feedback'
    | '/api/gemini-question'
    | '/api/generate-questions'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ChatNewRoute: typeof ChatNewRoute
  GeminiRoute: typeof GeminiRoute
  ApiGeminiFeedbackRoute: typeof ApiGeminiFeedbackRoute
  ApiGeminiQuestionRoute: typeof ApiGeminiQuestionRoute
  ApiGenerateQuestionsRoute: typeof ApiGenerateQuestionsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gemini': {
      id: '/gemini'
      path: '/gemini'
      fullPath: '/gemini'
      preLoaderRoute: typeof GeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-new': {
      id: '/chat-new'
      path: '/chat-new'
      fullPath: '/chat-new'
      preLoaderRoute: typeof ChatNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-questions': {
      id: '/api/generate-questions'
      path: '/api/generate-questions'
      fullPath: '/api/generate-questions'
      preLoaderRoute: typeof ApiGenerateQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemini-question': {
      id: '/api/gemini-question'
      path: '/api/gemini-question'
      fullPath: '/api/gemini-question'
      preLoaderRoute: typeof ApiGeminiQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gemini-feedback': {
      id: '/api/gemini-feedback'
      path: '/api/gemini-feedback'
      fullPath: '/api/gemini-feedback'
      preLoaderRoute: typeof ApiGeminiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ChatNewRoute: ChatNewRoute,
  GeminiRoute: GeminiRoute,
  ApiGeminiFeedbackRoute: ApiGeminiFeedbackRoute,
  ApiGeminiQuestionRoute: ApiGeminiQuestionRoute,
  ApiGenerateQuestionsRoute: ApiGenerateQuestionsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
